import { AuditLog } from "../types";

export const auditLogs: AuditLog[] = [
  {
    id: 1,
    timestamp: "2025-10-20 16:45:32",
    user: "김지현",
    userId: 52,
    action: "ROLE_UPDATED",
    actionKr: "역할 변경",
    target: "박근형 (user_id: 63)",
    details: {
      before: { role: "USER" },
      after: { role: "AGENTS_MANAGER" },
      reason: "에이전트 관리 역할 부여",
    },
    ipAddress: "192.168.1.100",
    severity: "info",
    status: "success",
  },
  {
    id: 2,
    timestamp: "2025-10-20 15:20:15",
    user: "김지현",
    userId: 52,
    action: "PERMISSION_GRANTED",
    actionKr: "역할 부여",
    target: "R&D그룹 (group_id: 59)",
    details: {
      permission: "MANAGE_AGENTS",
      resource: "/v1/agents",
    },
    ipAddress: "192.168.1.100",
    severity: "warning",
    status: "success",
  },
  {
    id: 3,
    timestamp: "2025-10-20 14:10:05",
    user: "이수진",
    userId: 78,
    action: "LOGIN_FAILED",
    actionKr: "로그인 실패",
    target: "인증 서버",
    details: {
      reason: "잘못된 비밀번호",
      attempts: 3,
    },
    ipAddress: "192.168.1.145",
    severity: "error",
    status: "failed",
  },
  {
    id: 4,
    timestamp: "2025-10-20 13:30:22",
    user: "김지현",
    userId: 52,
    action: "USER_LIMIT_UPDATED",
    actionKr: "사용량 제한 변경",
    target: "이수진 (user_id: 78)",
    details: {
      before: { chatLimit: 30000, embeddingLimit: 15000 },
      after: { chatLimit: 50000, embeddingLimit: 25000 },
    },
    ipAddress: "192.168.1.100",
    severity: "info",
    status: "success",
  },
  {
    id: 5,
    timestamp: "2025-10-20 11:15:40",
    user: "박근형",
    userId: 63,
    action: "GROUP_CREATED",
    actionKr: "그룹 생성",
    target: "AI개발팀 (group_id: 75)",
    details: {
      parent: "R&D그룹",
      members: [],
    },
    ipAddress: "192.168.1.112",
    severity: "info",
    status: "success",
  },
  {
    id: 6,
    timestamp: "2025-10-20 10:05:18",
    user: "김지현",
    userId: 52,
    action: "PASSPORT_VERIFIED",
    actionKr: "Passport 검증",
    target: "최민수 (user_id: 89)",
    details: {
      globalRoles: ["USER"],
      groupRoles: { "59": ["AGENTS_MANAGER"] },
      permissions: ["READ", "WRITE"],
    },
    ipAddress: "192.168.1.100",
    severity: "info",
    status: "success",
  },
];
