import { Document, DocumentFilter } from "../types";

// Mock 데이터
export const mockDocuments: Document[] = [
  {
    id: "1",
    title: "AI 프로젝트 기획서",
    authorId: "user1",
    authorName: "김철수",
    groupId: "group1",
    groupName: "개발팀",
    isEmbedded: true,
    embeddingStatus: "completed",
    tokenUsage: 1250,
    permissions: {
      isPublic: false,
      allowedGroups: [
        { groupId: "group1", groupName: "개발팀", level: "write" },
        { groupId: "group2", groupName: "기획팀", level: "read" },
      ],
      allowedUsers: [],
      ownerId: "user1",
    },
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-20"),
    fileSize: 2048000,
    fileType: "pdf",
    tags: ["기획", "AI", "프로젝트"],
  },
  {
    id: "2",
    title: "회사 보안 정책",
    authorId: "admin1",
    authorName: "관리자",
    groupId: "group-admin",
    groupName: "관리자",
    isEmbedded: true,
    embeddingStatus: "completed",
    tokenUsage: 3500,
    permissions: {
      isPublic: false,
      allowedGroups: [
        { groupId: "group-admin", groupName: "관리자", level: "admin" },
      ],
      allowedUsers: [{ userId: "user1", userName: "김철수", level: "read" }],
      ownerId: "admin1",
    },
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-25"),
    fileSize: 512000,
    fileType: "docx",
    tags: ["보안", "정책", "필독"],
  },
  {
    id: "3",
    title: "2024 마케팅 전략",
    authorId: "user2",
    authorName: "이영희",
    groupId: "group3",
    groupName: "마케팅팀",
    isEmbedded: false,
    embeddingStatus: "pending",
    tokenUsage: 0,
    permissions: {
      isPublic: true,
      allowedGroups: [],
      allowedUsers: [],
      ownerId: "user2",
    },
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
    fileSize: 1024000,
    fileType: "pptx",
    tags: ["마케팅", "전략"],
  },
  {
    id: "4",
    title: "개인정보 처리방침",
    authorId: "admin1",
    authorName: "관리자",
    groupId: "group-admin",
    groupName: "관리자",
    isEmbedded: true,
    embeddingStatus: "completed",
    tokenUsage: 2100,
    permissions: {
      isPublic: false,
      allowedGroups: [
        { groupId: "group-admin", groupName: "관리자", level: "admin" },
        { groupId: "group-legal", groupName: "법무팀", level: "write" },
      ],
      allowedUsers: [],
      ownerId: "admin1",
    },
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-02-10"),
    fileSize: 768000,
    fileType: "pdf",
    tags: ["법무", "개인정보", "필독"],
  },
  {
    id: "5",
    title: "API 문서",
    authorId: "user3",
    authorName: "박개발",
    groupId: "group1",
    groupName: "개발팀",
    isEmbedded: false,
    embeddingStatus: "processing",
    tokenUsage: 800,
    permissions: {
      isPublic: false,
      allowedGroups: [
        { groupId: "group1", groupName: "개발팀", level: "write" },
      ],
      allowedUsers: [{ userId: "user4", userName: "최테스터", level: "read" }],
      ownerId: "user3",
    },
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
    fileSize: 3072000,
    fileType: "md",
    tags: ["개발", "API", "문서"],
  },
];

// Mock 그룹 데이터
export const mockGroups = [
  { id: "group1", name: "개발팀" },
  { id: "group2", name: "기획팀" },
  { id: "group3", name: "마케팅팀" },
  { id: "group-admin", name: "관리자" },
  { id: "group-legal", name: "법무팀" },
];

// Mock 사용자 데이터
export const mockUsers = [
  { id: "user1", name: "김철수", email: "kim@example.com" },
  { id: "user2", name: "이영희", email: "lee@example.com" },
  { id: "user3", name: "박개발", email: "park@example.com" },
  { id: "user4", name: "최테스터", email: "choi@example.com" },
  { id: "admin1", name: "관리자", email: "admin@example.com" },
];
